name: Github-insights


on:
  push:
    branches: [ "main" ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v4

      - name: Create backend .env file
        run: |
          echo "TOKEN=${{ secrets.AUTH }}" >> backend/.env
          echo "SERVER1=${{ secrets.AUTH }}" >> backend/.env
          echo "SERVER2=${{ secrets.AUTH }}" >> backend/.env

      - name: Start containers
        run: docker compose up --build -d

      - name: Run Hello 200 test
        run: |
          echo "Running hello test"
          curl -f http://localhost:8000/api/message

      - name: Sleep for 10s
        run: sleep 10

      - name: Stop containers
        if: always()
        run: docker compose down
